//! Cargo.lock parser (TOML format).

use anyhow::Result;

use super::Ecosystem;
use crate::DependencyInfo;

pub fn parse_cargo_lock(content: &str) -> Result<Vec<DependencyInfo>> {
    let parsed: toml::Value = content.parse()?;
    let mut deps = Vec::new();

    if let Some(packages) = parsed.get("package").and_then(|v| v.as_array()) {
        // First pass: collect all package names that appear as dependencies of others.
        // A package is "direct" if it's NOT listed as a dependency of another package,
        // OR if it has no source (workspace member).
        let mut dep_of_others: std::collections::HashSet<String> =
            std::collections::HashSet::new();
        for pkg in packages {
            if let Some(pkg_deps) = pkg.get("dependencies").and_then(|v| v.as_array()) {
                for dep in pkg_deps {
                    // Dependencies can be strings like "serde" or "serde 1.0.200"
                    if let Some(dep_str) = dep.as_str() {
                        let dep_name = dep_str.split_whitespace().next().unwrap_or(dep_str);
                        dep_of_others.insert(dep_name.to_string());
                    }
                }
            }
        }

        for pkg in packages {
            let name = pkg.get("name").and_then(|v| v.as_str()).unwrap_or("");
            let version = pkg.get("version").and_then(|v| v.as_str()).unwrap_or("");
            let source = pkg.get("source").and_then(|v| v.as_str());

            if name.is_empty() || version.is_empty() {
                continue;
            }

            // Workspace members have no source — skip them entirely
            if source.is_none() {
                continue;
            }

            // A dependency is transitive if it only appears as a dep-of-a-dep.
            // Heuristic: if it appears in dep_of_others but the root package also
            // depends on it, it's still direct. We can't easily tell without Cargo.toml,
            // so we mark all deps-of-deps as transitive.
            let is_transitive = dep_of_others.contains(name);

            deps.push(DependencyInfo {
                name: name.to_string(),
                version: version.to_string(),
                ecosystem: Ecosystem::Cargo,
                transitive: is_transitive,
                parent: None,
            });
        }
    }

    Ok(deps)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_simple_cargo_lock() {
        let content = r#"
[[package]]
name = "serde"
version = "1.0.200"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "serde_json"
version = "1.0.120"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = ["serde"]
"#;

        let deps = parse_cargo_lock(content).unwrap();
        assert_eq!(deps.len(), 2);
        assert_eq!(deps[0].name, "serde");
        assert_eq!(deps[0].ecosystem, Ecosystem::Cargo);
    }

    #[test]
    fn parse_cargo_lock_empty() {
        let content = "# This file is automatically generated by Cargo.\n";
        let deps = parse_cargo_lock(content).unwrap();
        assert!(deps.is_empty());
    }

    #[test]
    fn parse_cargo_lock_with_dependencies_array() {
        let content = r#"
[[package]]
name = "serde"
version = "1.0.200"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "serde_derive",
]

[[package]]
name = "serde_derive"
version = "1.0.200"
source = "registry+https://github.com/rust-lang/crates.io-index"
"#;
        let deps = parse_cargo_lock(content).unwrap();
        assert_eq!(deps.len(), 2);
        // serde_derive is listed as a dependency of serde, so it's transitive
        let derive = deps.iter().find(|d| d.name == "serde_derive").unwrap();
        assert!(derive.transitive);
        // serde is not a dep of anyone else, so it's direct
        let serde = deps.iter().find(|d| d.name == "serde").unwrap();
        assert!(!serde.transitive);
    }
}
