//! Lockfile parsing dispatcher.

pub mod cargo;
pub mod go;
pub mod npm;
pub mod poetry;
pub mod yarn;

use std::path::Path;

use anyhow::Result;
use serde::Serialize;

use crate::DependencyInfo;

/// Supported package ecosystems.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize)]
pub enum Ecosystem {
    Cargo,
    Npm,
    Yarn,
    Poetry,
    Go,
}

impl Ecosystem {
    /// Return the OSV ecosystem string for API queries.
    pub fn osv_ecosystem(&self) -> &'static str {
        match self {
            Ecosystem::Cargo => "crates.io",
            Ecosystem::Npm | Ecosystem::Yarn => "npm",
            Ecosystem::Poetry => "PyPI",
            Ecosystem::Go => "Go",
        }
    }
}

/// Parse a lockfile at the given path using the appropriate parser.
pub fn parse(path: &Path, eco: Ecosystem) -> Result<Vec<DependencyInfo>> {
    let content = std::fs::read_to_string(path)?;
    match eco {
        Ecosystem::Cargo => cargo::parse_cargo_lock(&content),
        Ecosystem::Npm => npm::parse_package_lock(&content),
        Ecosystem::Yarn => yarn::parse_yarn_lock(&content),
        Ecosystem::Poetry => poetry::parse_poetry_lock(&content),
        Ecosystem::Go => go::parse_go_sum(&content),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn osv_ecosystem_mappings() {
        assert_eq!(Ecosystem::Cargo.osv_ecosystem(), "crates.io");
        assert_eq!(Ecosystem::Npm.osv_ecosystem(), "npm");
        assert_eq!(Ecosystem::Yarn.osv_ecosystem(), "npm");
        assert_eq!(Ecosystem::Poetry.osv_ecosystem(), "PyPI");
        assert_eq!(Ecosystem::Go.osv_ecosystem(), "Go");
    }

    #[test]
    fn parse_missing_file() {
        let result = parse(Path::new("/nonexistent/lockfile"), Ecosystem::Cargo);
        assert!(result.is_err());
    }

    #[test]
    fn parse_cargo_lock_via_dispatch() {
        let tmp = tempfile::TempDir::new().unwrap();
        let lockfile = tmp.path().join("Cargo.lock");
        std::fs::write(
            &lockfile,
            r#"# This file is automatically generated by Cargo.
[[package]]
name = "serde"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
"#,
        )
        .unwrap();
        let deps = parse(&lockfile, Ecosystem::Cargo).unwrap();
        assert!(!deps.is_empty());
        assert!(deps.iter().any(|d| d.name == "serde"));
    }

    #[test]
    fn ecosystem_equality() {
        assert_eq!(Ecosystem::Cargo, Ecosystem::Cargo);
        assert_ne!(Ecosystem::Cargo, Ecosystem::Npm);
    }
}
