//! yarn.lock parser (line-based custom format).

use anyhow::Result;

use super::Ecosystem;
use crate::DependencyInfo;

pub fn parse_yarn_lock(content: &str) -> Result<Vec<DependencyInfo>> {
    let mut deps = Vec::new();
    let mut current_name = String::new();
    let mut current_version = String::new();

    for line in content.lines() {
        let trimmed = line.trim();

        // Skip comments and empty lines
        if trimmed.starts_with('#') || trimmed.is_empty() {
            continue;
        }

        // Package header lines look like: "package-name@^1.0.0":
        // or: package-name@^1.0.0, package-name@~1.0.0:
        if !trimmed.starts_with(' ') && trimmed.ends_with(':') {
            // Save previous entry
            if !current_name.is_empty() && !current_version.is_empty() {
                deps.push(DependencyInfo {
                    name: current_name.clone(),
                    version: current_version.clone(),
                    ecosystem: Ecosystem::Yarn,
                    transitive: false,
                    parent: None,
                });
            }

            // Parse the package name from the header
            let header = trimmed.trim_end_matches(':');
            // Take the first specifier (before any comma)
            let first_spec = header.split(',').next().unwrap_or(header).trim();
            // Remove quotes
            let first_spec = first_spec.trim_matches('"');
            // Split on @ to get name (handle scoped packages like @scope/pkg)
            current_name = if first_spec.starts_with('@') {
                // Scoped: @scope/pkg@version
                match first_spec[1..].find('@') {
                    Some(idx) => first_spec[..idx + 1].to_string(),
                    None => first_spec.to_string(),
                }
            } else {
                match first_spec.find('@') {
                    Some(idx) => first_spec[..idx].to_string(),
                    None => first_spec.to_string(),
                }
            };
            current_version.clear();
        }

        // Version line: "  version "1.0.0""
        if trimmed.starts_with("version ") {
            current_version = trimmed
                .strip_prefix("version ")
                .unwrap_or("")
                .trim_matches('"')
                .to_string();
        }
    }

    // Don't forget the last entry
    if !current_name.is_empty() && !current_version.is_empty() {
        deps.push(DependencyInfo {
            name: current_name,
            version: current_version,
            ecosystem: Ecosystem::Yarn,
            transitive: false,
            parent: None,
        });
    }

    Ok(deps)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_simple_yarn_lock() {
        let content = r#"# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT.

express@^4.18.0:
  version "4.18.2"
  resolved "https://registry.yarnpkg.com/express/-/express-4.18.2.tgz"

lodash@^4.17.0:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"
"#;

        let deps = parse_yarn_lock(content).unwrap();
        assert_eq!(deps.len(), 2);
        assert_eq!(deps[0].name, "express");
        assert_eq!(deps[0].version, "4.18.2");
        assert_eq!(deps[1].name, "lodash");
    }

    #[test]
    fn parse_yarn_lock_empty() {
        let content = "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT.\n";
        let deps = parse_yarn_lock(content).unwrap();
        assert!(deps.is_empty());
    }

    #[test]
    fn parse_yarn_lock_missing_version() {
        let content = r#"# yarn lockfile v1

express@^4.18.0:
  resolved "https://registry.yarnpkg.com/express/-/express-4.18.2.tgz"

lodash@^4.17.0:
  version "4.17.21"
"#;
        let deps = parse_yarn_lock(content).unwrap();
        // express has no version line, should be skipped or handled gracefully
        assert!(deps.len() <= 2);
        if !deps.is_empty() {
            assert!(deps.iter().any(|d| d.name == "lodash"));
        }
    }
}
